spring.application.name=config-server
server.port=8888

# Configuración del repositorio Git remoto
spring.cloud.config.server.git.uri=https://github.com/EdwinIvanS/test-config.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
logging.level.org.springframework.cloud.config=DEBUG
spring.cloud.config.server.git.force-pull: true